# Dockerfile for a Python application
FROM python:3.11-slim

# download  & install pipenv
RUN pip install --upgrade pip && pip install pipenv

# working directory
WORKDIR /src

# copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock /src/

# install dependencies
RUN pipenv install --deploy --ignore-pipfile

# copy the rest of the application code
COPY . /src/

