services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    container_name: druid-postgres
    environment:
      - POSTGRES_PASSWORD=Password
      - POSTGRES_USER=druid
      - POSTGRES_DB=metadata
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "druid", "-d", "metadata" ]
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper:
    image: zookeeper:3.8
    container_name: druid-zookeeper
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]
      interval: 5s
      retries: 10

  # --- DATA ENGINE (DRUID) ---
  druid:
    image: apache/druid:28.0.1
    container_name: druid
    user: root
    depends_on:
      postgres: { condition: service_healthy }
      zookeeper: { condition: service_healthy }
    ports:
      - "8888:8888"
      - "8081:8081"
      - "8082:8082"
    configs:
      - source: druid_common_config
        target: /opt/druid/conf/druid/single-server/micro-quickstart/_common/common.runtime.properties
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        echo "==> Configuration de Druid..."
        mkdir -p /opt/druid/var/druid/indexing-logs /opt/druid/var/druid/segments /opt/druid/var/sv
        cd /opt/druid
        bin/run-druid coordinator-overlord conf/druid/single-server/micro-quickstart >> /opt/druid/var/sv/coordinator-overlord.log 2>&1 &
        sleep 5
        bin/run-druid broker conf/druid/single-server/micro-quickstart >> /opt/druid/var/sv/broker.log 2>&1 &
        bin/run-druid router conf/druid/single-server/micro-quickstart >> /opt/druid/var/sv/router.log 2>&1 &
        bin/run-druid historical conf/druid/single-server/micro-quickstart >> /opt/druid/var/sv/historical.log 2>&1 &
        sleep 3
        bin/run-druid middleManager conf/druid/single-server/micro-quickstart >> /opt/druid/var/sv/middleManager.log 2>&1 &
        tail -f /opt/druid/var/sv/coordinator-overlord.log
    volumes:
      - ./src/data:/opt/druid/var/druid/data
      - druid_segments:/opt/druid/var/druid/segments
      - druid_indexing_logs:/opt/druid/var/druid/indexing-logs

  # --- VISUALIZATION (SUPERSET) ---
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=votre_cle_secrete_123
      - SQLALCHEMY_DATABASE_URI=postgresql://druid:Password@postgres:5432/superset
    ports:
      - "8088:8088"
    depends_on:
      postgres: { condition: service_healthy }

  # --- ORCHESTRATION (AIRFLOW) ---
  airflow:
    image: apache/airflow:2.7.1-python3.11
    container_name: airflow
    user: root
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://druid:Password@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=ma_super_cle_secrete_987
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - _AIRFLOW_WWW_USER_EMAIL=admin@fab.org
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres: { condition: service_healthy }

# --- CONFIGURATION DRUID  ---
configs:
  druid_common_config:
    content: |
      druid.extensions.loadList=["druid-histogram","druid-datasketches","druid-lookups-cached-global","postgresql-metadata-storage","druid-parquet-extensions"]
      druid.zk.service.host=zookeeper
      druid.zk.paths.base=/druid
      druid.metadata.storage.type=postgresql
      druid.metadata.storage.connector.connectURI=jdbc:postgresql://postgres:5432/metadata
      druid.metadata.storage.connector.user=druid
      druid.metadata.storage.connector.password=Password
      druid.storage.type=local
      druid.storage.storageDirectory=/opt/druid/var/druid/segments
      druid.indexer.logs.type=file
      druid.indexer.logs.directory=/opt/druid/var/druid/indexing-logs
      druid.emitter=noop

volumes:
  druid_metadata:
  druid_segments:
  druid_indexing_logs:
